import './LegalPage.css'

const updatedDate = 'August 14, 2026'

const termsSections = [
  {
    title: '1. Acceptance of these terms',
    content: 'These Terms of Use govern your use of the Genk Studios website and any enquiry, conversation or service engagement that follows. By accessing this website, you agree to these terms. If you do not agree, please do not use the website.',
  },
  {
    title: '2. Our services',
    content: 'Genk Studios is a digital product studio providing services that may include strategy, branding, website design and development, web application development, e-commerce, AI and automation. A proposal, statement of work or written agreement will define the scope, timing, deliverables, fees and terms for any paid project. Website content is informational and does not create a client relationship or obligation to provide services.',
  },
  {
    title: '3. Enquiries and project information',
    content: 'When you contact us, you agree to provide accurate information and to use the website lawfully. Please do not submit confidential, sensitive or proprietary information until we have agreed in writing to receive it. An enquiry does not guarantee availability, a quotation or an engagement.',
  },
  {
    title: '4. Intellectual property',
    content: 'Unless stated otherwise, the website, its code, design, copy, logos, graphics, trademarks and other content are owned by Genk Studios or used with permission. You may view and share website content for personal or internal business purposes, but you may not copy, reproduce, adapt, sell, distribute or create derivative works without prior written permission. Project deliverable ownership is governed by the applicable client agreement, not these website terms.',
  },
  {
    title: '5. Acceptable use',
    content: 'You must not interfere with the website, attempt to gain unauthorized access, introduce harmful code, scrape content at scale, impersonate another person, misuse enquiry channels or use the website in violation of applicable law. We may restrict access where we reasonably believe these terms have been breached.',
  },
  {
    title: '6. Third-party services and links',
    content: 'This website may contain links to third-party websites, platforms or content. Those services are controlled by their respective providers, and we are not responsible for their availability, security, content or privacy practices. Your use of third-party services is subject to their terms and policies.',
  },
  {
    title: '7. Disclaimer and limitation of liability',
    content: 'We aim to keep the website accurate, secure and available, but provide it on an “as is” and “as available” basis to the fullest extent permitted by law. We do not guarantee uninterrupted access, error-free content or that the website will meet every purpose. Genk Studios will not be liable for indirect, incidental, special, consequential or punitive damages arising from use of, or inability to use, the website.',
  },
  {
    title: '8. Changes and governing law',
    content: 'We may update these terms as our website or services evolve. Changes take effect when posted with a revised effective date. These terms are governed by the laws applicable in the jurisdiction where Genk Studios is established, without regard to conflict-of-law rules. For questions, email genkstudios05@gmail.com.',
  },
]

const privacySections = [
  {
    title: '1. Information we collect',
    content: 'We collect information you choose to provide, including your name, email address, company details and project information when you contact us. We may also collect limited technical information generated by your browser or device, such as IP address, browser type, pages viewed, referral source and approximate location. If analytics or cookie tools are added, they may collect usage information as described in their own policies.',
  },
  {
    title: '2. How we use your information',
    content: 'We use your information to respond to enquiries, assess potential projects, communicate about our services, improve the website, maintain security and meet legal obligations. We do not sell personal information. We only use information for marketing where permitted by law or where you have given the relevant consent.',
  },
  {
    title: '3. Legal basis and retention',
    content: 'Where applicable, we process personal information because it is necessary to respond to your request, pursue our legitimate interest in operating and improving our business, comply with legal obligations or because you have consented. We retain enquiry information only for as long as reasonably necessary for these purposes, including follow-up, recordkeeping and legal compliance.',
  },
  {
    title: '4. Sharing information',
    content: 'We may share information with trusted service providers that help us host the website, manage communications, provide analytics or operate our business. These providers may process information only on our instructions and for the relevant service. We may also disclose information where required by law, to protect rights and safety, or as part of a business transfer.',
  },
  {
    title: '5. Cookies and analytics',
    content: 'Cookies are small files placed on your device that can support website functionality and help us understand usage. You can control cookies through your browser settings. Disabling cookies may affect certain website features. If we introduce non-essential analytics or advertising cookies, we will provide notice and any consent controls required by applicable law.',
  },
  {
    title: '6. Security',
    content: 'We use reasonable technical and organizational measures to protect information. No online system can be completely secure, so please avoid sending sensitive personal information through the general project enquiry form. If you believe your information has been compromised, contact us promptly.',
  },
  {
    title: '7. Your rights',
    content: 'Depending on your location, you may have the right to request access to, correction of, deletion of, restriction of or portability of your personal information, and to object to certain processing. You may also withdraw consent where processing is based on consent. To make a request, email genkstudios05@gmail.com. We may need to verify your identity before responding.',
  },
  {
    title: '8. Children and policy updates',
    content: 'Our website and services are not directed to children, and we do not knowingly collect personal information from children. We may update this policy to reflect changes to our practices or legal obligations. The latest version will always be posted here with an updated effective date. For privacy questions or requests, contact genkstudios05@gmail.com.',
  },
]

function LegalPage({ type }) {
  const isTerms = type === 'terms'
  const title = isTerms ? 'Terms of Use' : 'Privacy Policy'
  const introduction = isTerms
    ? 'The terms that govern your use of the Genk Studios website.'
    : 'How Genk Studios collects, uses and protects your information.'
  const sections = isTerms ? termsSections : privacySections

  return (
    <main className="legal-page">
      <header className="legal-header">
        <a href="/" className="legal-brand" aria-label="Genk Studios home">
          <span className="legal-mark" aria-hidden="true">
            <svg viewBox="0 0 28 28" fill="none">
              <path
                d="M19.9 9.1a6.6 6.6 0 1 0 1.4 6.1h-5"
                stroke="currentColor"
                strokeWidth="2.3"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </span>
          <span>
            Genk <span className="legal-brand-dim">Studios</span>
          </span>
        </a>
        <a href="/" className="legal-home-link">Back to home</a>
      </header>

      <article className="legal-content">
        <div className="legal-kicker">Genk Studios</div>
        <h1>{title}</h1>
        <p className="legal-intro">{introduction}</p>
        <p className="legal-updated">Effective date: {updatedDate}</p>

        <div className="legal-sections">
          {sections.map((section) => (
            <section key={section.title}>
              <h2>{section.title}</h2>
              <p>{section.content}</p>
            </section>
          ))}
        </div>
      </article>

      <footer className="legal-footer">
        <span>© 2026 Genk Studios</span>
        <div>
          <a href="/terms">Terms of Use</a>
          <a href="/privacy">Privacy</a>
        </div>
      </footer>
    </main>
  )
}

export default LegalPage